import { z } from "zod";

import {
  ActorReferenceSchema,
  ContentHashSchema,
  IsoDateTimeSchema,
  SafeMetadataSchema,
} from "./common.js";
import {
  AuditEventIdSchema,
  OrganisationIdSchema,
  OutboxEventIdSchema,
  ProjectIdSchema,
} from "./ids.js";

export const AuditEventTypeSchema = z.enum([
  "organisation.created",
  "project.created",
  "membership.created",
  "membership.revoked",
  "invitation.issued",
  "invitation.consumed",
  "invitation.revoked",
  "question.created",
  "question.assigned",
  "question_response.submitted",
  "source_fragment.created",
  "artifact_version.created",
  "artifact_version.state_changed",
  "approval_request.opened",
  "approval_request.stale",
  "approval_decision.recorded",
  "approval.revoked",
  "sprint.created",
  "execution_plan_version.created",
  "execution_cycle.requested",
  "execution_cycle.state_changed",
  "execution_work_item_claim.acquired",
  "execution_work_item_claim.conflict",
  "execution_work_item_claim.released",
  "runner_capability.issued",
  "runner_capability.renewed",
  "runner_capability.revoked",
  "runner_environment.state_changed",
  "agent_action.recorded",
  "agent_action_denied",
  "execution_limit.reached",
  "execution_checkpoint.recorded",
  "execution_test_run.recorded",
  "execution_work_report.created",
  "execution_review.recorded",
  "runner_cleanup.completed",
  "runner_cleanup.failed",
  "change_proposal.created",
  "change.applied",
  "release.recorded",
  "prohibited_content.detected",
  "prohibited_content.contained",
  "prohibited_content.remediated",
  "demonstration_comparison.completed",
]);

export const AuditEventSchema = z.object({
  id: AuditEventIdSchema,
  organisationId: OrganisationIdSchema,
  projectId: ProjectIdSchema.nullable(),
  sequence: z.number().int().positive(),
  eventType: AuditEventTypeSchema,
  actor: ActorReferenceSchema,
  aggregateType: z.string().min(1).max(120),
  aggregateId: z.string().uuid(),
  aggregateVersion: z.number().int().nonnegative().nullable(),
  beforeHash: ContentHashSchema.nullable(),
  afterHash: ContentHashSchema.nullable(),
  safeMetadata: SafeMetadataSchema,
  correlationId: z.string().uuid(),
  causationId: z.string().uuid().nullable(),
  occurredAt: IsoDateTimeSchema,
});

export const DomainEventTypeSchema = z.enum([
  "organisation.created.v1",
  "project.created.v1",
  "invitation.issued.v1",
  "invitation.consumed.v1",
  "question.assigned.v1",
  "question_response.submitted.v1",
  "artifact_version.created.v1",
  "approval_request.opened.v1",
  "approval_request.stale.v1",
  "approval_decision.recorded.v1",
  "approval.revoked.v1",
  "sprint.ready.v1",
  "execution_plan.approved.v1",
  "execution_cycle.requested.v1",
  "execution_cycle.state_changed.v1",
  "execution_work_item_claim.acquired.v1",
  "execution_work_item_claim.conflict.v1",
  "execution_work_item_claim.released.v1",
  "runner_capability.issued.v1",
  "runner_capability.revoked.v1",
  "runner_environment.state_changed.v1",
  "agent_action_denied.v1",
  "execution_checkpoint.opened.v1",
  "execution_test_run.completed.v1",
  "execution_work_report.created.v1",
  "execution_review.recorded.v1",
  "runner_cleanup.failed.v1",
  "change.applied.v1",
  "release.recorded.v1",
  "prohibited_content.detected.v1",
  "demonstration_comparison.completed.v1",
]);

export const DomainEventEnvelopeSchema = z.object({
  id: OutboxEventIdSchema,
  type: DomainEventTypeSchema,
  version: z.literal(1),
  organisationId: OrganisationIdSchema,
  projectId: ProjectIdSchema.optional(),
  aggregateType: z.string().min(1).max(120),
  aggregateId: z.string().uuid(),
  payload: z.record(z.string(), z.unknown()),
  correlationId: z.string().uuid(),
  causationId: z.string().uuid().optional(),
  occurredAt: IsoDateTimeSchema,
});

export const OutboxEventSchema = DomainEventEnvelopeSchema.extend({
  availableAt: IsoDateTimeSchema,
  attempts: z.number().int().nonnegative(),
  deliveredAt: IsoDateTimeSchema.nullable(),
  deadLetteredAt: IsoDateTimeSchema.nullable(),
});

export type AuditEvent = z.infer<typeof AuditEventSchema>;
export type DomainEventEnvelope = z.infer<typeof DomainEventEnvelopeSchema>;
