import { sql } from "drizzle-orm";
import { bigint, check, foreignKey, index, integer, jsonb, numeric, pgTable, text, timestamp, unique, uniqueIndex, uuid } from "drizzle-orm/pg-core";

import { artifactVersions } from "./artifacts.js";
import { createdAt, id, lockVersion, requiredJsonObject } from "./common.js";
import { projectMemberships, projects } from "./identity.js";
import { repositories, repositoryAccessSnapshots } from "./repositories.js";
import { workItems } from "./agile.js";

export const executionPlans = pgTable(
  "execution_plans",
  {
    id: id(),
    organisationId: uuid("organisation_id").notNull(),
    projectId: uuid("project_id").notNull(),
    key: text("key").notNull(),
    title: text("title").notNull(),
    currentVersionId: uuid("current_version_id"),
    createdByActorId: uuid("created_by_actor_id"),
    createdAt: createdAt(),
    archivedAt: timestamp("archived_at", { withTimezone: true }),
  },
  (t) => [
    unique("execution_plans_org_id_uq").on(t.organisationId, t.id),
    unique("execution_plans_project_id_uq").on(t.organisationId, t.projectId, t.id),
    unique("execution_plans_project_key_uq").on(t.organisationId, t.projectId, t.key),
    foreignKey({ columns: [t.organisationId, t.projectId], foreignColumns: [projects.organisationId, projects.id], name: "execution_plans_project_fk" }),
  ],
);

export const executionPlanVersions = pgTable(
  "execution_plan_versions",
  {
    id: id(),
    organisationId: uuid("organisation_id").notNull(),
    projectId: uuid("project_id").notNull(),
    executionPlanId: uuid("execution_plan_id").notNull(),
    versionNumber: integer("version_number").notNull(),
    status: text("status").default("draft").notNull(),
    objective: text("objective").notNull(),
    projectPlanArtifactVersionId: uuid("project_plan_artifact_version_id").notNull(),
    repositoryId: uuid("repository_id").notNull(),
    repositoryAccessSnapshotId: uuid("repository_access_snapshot_id").notNull(),
    approvedCommitSha: text("approved_commit_sha").notNull(),
    branchStrategy: text("branch_strategy").notNull(),
    branchName: text("branch_name").notNull(),
    pathPolicy: requiredJsonObject("path_policy"),
    networkPolicy: requiredJsonObject("network_policy"),
    toolPolicy: requiredJsonObject("tool_policy"),
    secretPolicy: requiredJsonObject("secret_policy"),
    acceptancePolicy: requiredJsonObject("acceptance_policy"),
    testPolicy: requiredJsonObject("test_policy"),
    stopPolicy: requiredJsonObject("stop_policy"),
    reviewPolicy: requiredJsonObject("review_policy"),
    policySchemaVersion: integer("policy_schema_version").notNull(),
    maxTurns: integer("max_turns").notNull(),
    maxTasks: integer("max_tasks").notNull(),
    maxInputTokens: bigint("max_input_tokens", { mode: "number" }).notNull(),
    maxOutputTokens: bigint("max_output_tokens", { mode: "number" }).notNull(),
    maxCostMinorUnits: bigint("max_cost_minor_units", { mode: "number" }).notNull(),
    currency: text("currency").notNull(),
    maxDurationSeconds: integer("max_duration_seconds").notNull(),
    canonicalPayload: jsonb("canonical_payload").$type<Record<string, unknown>>().notNull(),
    contentHash: text("content_hash").notNull(),
    supersedesVersionId: uuid("supersedes_version_id"),
    createdByActorId: uuid("created_by_actor_id"),
    createdAt: createdAt(),
  },
  (t) => [
    unique("execution_plan_versions_org_id_uq").on(t.organisationId, t.id),
    unique("execution_plan_versions_project_id_uq").on(t.organisationId, t.projectId, t.id),
    unique("execution_plan_versions_plan_number_uq").on(t.organisationId, t.executionPlanId, t.versionNumber),
    unique("execution_plan_versions_plan_hash_uq").on(t.organisationId, t.executionPlanId, t.contentHash),
    foreignKey({ columns: [t.organisationId, t.projectId, t.executionPlanId], foreignColumns: [executionPlans.organisationId, executionPlans.projectId, executionPlans.id], name: "execution_plan_versions_plan_fk" }),
    foreignKey({ columns: [t.organisationId, t.projectId, t.projectPlanArtifactVersionId], foreignColumns: [artifactVersions.organisationId, artifactVersions.projectId, artifactVersions.id], name: "execution_plan_versions_project_plan_fk" }),
    foreignKey({ columns: [t.organisationId, t.repositoryId], foreignColumns: [repositories.organisationId, repositories.id], name: "execution_plan_versions_repository_fk" }),
    foreignKey({ columns: [t.organisationId, t.projectId, t.repositoryAccessSnapshotId], foreignColumns: [repositoryAccessSnapshots.organisationId, repositoryAccessSnapshots.projectId, repositoryAccessSnapshots.id], name: "execution_plan_versions_access_snapshot_fk" }),
    index("execution_plan_versions_plan_history_idx").on(t.organisationId, t.executionPlanId, t.versionNumber),
    check("execution_plan_versions_status_ck", sql`${t.status} in ('draft','frozen','approval_pending','approved','superseded','withdrawn')`),
    check("execution_plan_versions_limits_ck", sql`${t.maxTurns} > 0 and ${t.maxTasks} > 0 and ${t.maxInputTokens} > 0 and ${t.maxOutputTokens} > 0 and ${t.maxCostMinorUnits} >= 0 and ${t.maxDurationSeconds} > 0`),
  ],
);

export const executionCycles = pgTable(
  "execution_cycles",
  {
    id: id(),
    organisationId: uuid("organisation_id").notNull(),
    projectId: uuid("project_id").notNull(),
    executionPlanVersionId: uuid("execution_plan_version_id").notNull(),
    state: text("state").default("requested").notNull(),
    stopReason: text("stop_reason"),
    requestIdempotencyKey: text("request_idempotency_key").notNull(),
    approvalSnapshotId: uuid("approval_snapshot_id").notNull(),
    currentRunnerEnvironmentId: uuid("current_runner_environment_id"),
    requestedByActorId: uuid("requested_by_actor_id").notNull(),
    requestedAt: timestamp("requested_at", { withTimezone: true }).defaultNow().notNull(),
    startedAt: timestamp("started_at", { withTimezone: true }),
    stoppedAt: timestamp("stopped_at", { withTimezone: true }),
    lockVersion: lockVersion(),
  },
  (t) => [
    unique("execution_cycles_org_id_uq").on(t.organisationId, t.id),
    unique("execution_cycles_project_id_uq").on(t.organisationId, t.projectId, t.id),
    unique("execution_cycles_plan_version_uq").on(t.executionPlanVersionId),
    unique("execution_cycles_project_idempotency_uq").on(t.organisationId, t.projectId, t.requestIdempotencyKey),
    foreignKey({ columns: [t.organisationId, t.projectId, t.executionPlanVersionId], foreignColumns: [executionPlanVersions.organisationId, executionPlanVersions.projectId, executionPlanVersions.id], name: "execution_cycles_plan_version_fk" }),
    index("execution_cycles_state_time_idx").on(t.organisationId, t.state, t.requestedAt),
    check("execution_cycles_state_ck", sql`${t.state} in ('requested','authorising','queued','provisioning','running','checkpoint_waiting','human_input_required','testing','reporting','awaiting_review','completed','cancelling','cancelled','failed','recovery_required')`),
    check("execution_cycles_stop_reason_ck", sql`${t.stopReason} is null or ${t.stopReason} in ('checkpoint_reached','human_input_required','scope_violation','token_limit','cost_limit','turn_limit','task_limit','time_limit','tests_failed','approval_revoked','membership_revoked','repository_access_lost','material_change','user_cancelled','runner_crash','completed')`),
    check("execution_cycles_terminal_time_ck", sql`${t.state} not in ('completed','cancelled','failed') or ${t.stoppedAt} is not null`),
    check("execution_cycles_completed_reason_ck", sql`${t.state} <> 'completed' or ${t.stopReason} = 'completed'`),
  ],
);

export const executionCycleWorkItems = pgTable(
  "execution_cycle_work_items",
  {
    id: id(),
    organisationId: uuid("organisation_id").notNull(),
    projectId: uuid("project_id").notNull(),
    executionCycleId: uuid("execution_cycle_id").notNull(),
    workItemId: uuid("work_item_id").notNull(),
    frozenManifest: requiredJsonObject("frozen_manifest"),
    createdAt: createdAt(),
  },
  (t) => [
    unique("execution_cycle_work_items_org_id_uq").on(t.organisationId, t.id),
    unique("execution_cycle_work_items_cycle_work_uq").on(t.organisationId, t.executionCycleId, t.workItemId),
    foreignKey({ columns: [t.organisationId, t.projectId, t.executionCycleId], foreignColumns: [executionCycles.organisationId, executionCycles.projectId, executionCycles.id], name: "execution_cycle_work_items_cycle_fk" }),
    foreignKey({ columns: [t.organisationId, t.projectId, t.workItemId], foreignColumns: [workItems.organisationId, workItems.projectId, workItems.id], name: "execution_cycle_work_items_work_item_fk" }),
  ],
);

export const executionWorkItemClaims = pgTable(
  "execution_work_item_claims",
  {
    id: id(),
    organisationId: uuid("organisation_id").notNull(),
    projectId: uuid("project_id").notNull(),
    executionCycleId: uuid("execution_cycle_id").notNull(),
    workItemId: uuid("work_item_id").notNull(),
    claimedAt: timestamp("claimed_at", { withTimezone: true }).defaultNow().notNull(),
    releasedAt: timestamp("released_at", { withTimezone: true }),
    releaseReason: text("release_reason"),
    releaseAuthorisation: jsonb("release_authorisation").$type<Record<string, unknown>>(),
    createdAt: createdAt(),
  },
  (t) => [
    unique("execution_work_item_claims_org_id_uq").on(t.organisationId, t.id),
    unique("execution_work_item_claims_cycle_work_uq").on(t.organisationId, t.executionCycleId, t.workItemId),
    uniqueIndex("execution_work_item_claims_active_work_uq").on(t.organisationId, t.workItemId).where(sql`${t.releasedAt} is null`),
    foreignKey({ columns: [t.organisationId, t.projectId, t.executionCycleId], foreignColumns: [executionCycles.organisationId, executionCycles.projectId, executionCycles.id], name: "execution_work_item_claims_cycle_fk" }),
    foreignKey({ columns: [t.organisationId, t.projectId, t.workItemId], foreignColumns: [workItems.organisationId, workItems.projectId, workItems.id], name: "execution_work_item_claims_work_item_fk" }),
    check("execution_work_item_claims_release_pair_ck", sql`(${t.releasedAt} is null and ${t.releaseReason} is null and ${t.releaseAuthorisation} is null) or (${t.releasedAt} is not null and ${t.releaseReason} in ('required_review_completed','safely_cancelled','authorised_failure_recovery','authorised_change_removed_work') and ${t.releaseAuthorisation} is not null)`),
    check("execution_work_item_claims_release_time_ck", sql`${t.releasedAt} is null or ${t.releasedAt} >= ${t.claimedAt}`),
  ],
);

export const runnerEnvironments = pgTable(
  "runner_environments",
  {
    id: id(),
    organisationId: uuid("organisation_id").notNull(),
    projectId: uuid("project_id").notNull(),
    executionCycleId: uuid("execution_cycle_id").notNull(),
    provider: text("provider").notNull(),
    runtimeIdentity: text("runtime_identity"),
    state: text("state").default("requested").notNull(),
    workspaceReference: text("workspace_reference"),
    preservedPatchObjectReference: text("preserved_patch_object_reference"),
    cleanupAttempts: integer("cleanup_attempts").default(0).notNull(),
    cleanupErrorCode: text("cleanup_error_code"),
    cleanupSafeSummary: text("cleanup_safe_summary"),
    requestedAt: timestamp("requested_at", { withTimezone: true }).defaultNow().notNull(),
    creatingAt: timestamp("creating_at", { withTimezone: true }),
    readyAt: timestamp("ready_at", { withTimezone: true }),
    activeAt: timestamp("active_at", { withTimezone: true }),
    revokingAt: timestamp("revoking_at", { withTimezone: true }),
    destroyingAt: timestamp("destroying_at", { withTimezone: true }),
    destroyedAt: timestamp("destroyed_at", { withTimezone: true }),
    lockVersion: lockVersion(),
  },
  (t) => [
    unique("runner_environments_org_id_uq").on(t.organisationId, t.id),
    unique("runner_environments_project_id_uq").on(t.organisationId, t.projectId, t.id),
    foreignKey({ columns: [t.organisationId, t.projectId, t.executionCycleId], foreignColumns: [executionCycles.organisationId, executionCycles.projectId, executionCycles.id], name: "runner_environments_cycle_fk" }),
    uniqueIndex("runner_environments_active_cycle_uq").on(t.organisationId, t.executionCycleId).where(sql`${t.state} not in ('destroyed','cleanup_failed')`),
    index("runner_environments_state_idx").on(t.organisationId, t.state, t.requestedAt),
    check("runner_environments_state_ck", sql`${t.state} in ('requested','creating','ready','active','revoking','destroying','destroyed','cleanup_failed')`),
    check("runner_environments_destroyed_ck", sql`(${t.state} = 'destroyed') = (${t.destroyedAt} is not null)`),
    check("runner_environments_cleanup_error_ck", sql`${t.state} <> 'cleanup_failed' or (${t.cleanupErrorCode} is not null and ${t.cleanupSafeSummary} is not null)`),
  ],
);

export const runnerCapabilityGrants = pgTable(
  "runner_capability_grants",
  {
    id: id(),
    organisationId: uuid("organisation_id").notNull(),
    projectId: uuid("project_id").notNull(),
    executionCycleId: uuid("execution_cycle_id").notNull(),
    runnerEnvironmentId: uuid("runner_environment_id").notNull(),
    tokenHash: text("token_hash").notNull(),
    jtiHash: text("jti_hash").notNull(),
    scope: requiredJsonObject("scope"),
    scopeHash: text("scope_hash").notNull(),
    issuedAt: timestamp("issued_at", { withTimezone: true }).defaultNow().notNull(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    revokedAt: timestamp("revoked_at", { withTimezone: true }),
    revokedReason: text("revoked_reason"),
    renewalParentGrantId: uuid("renewal_parent_grant_id"),
  },
  (t) => [
    unique("runner_capability_grants_org_id_uq").on(t.organisationId, t.id),
    unique("runner_capability_grants_token_hash_uq").on(t.tokenHash),
    unique("runner_capability_grants_jti_hash_uq").on(t.jtiHash),
    uniqueIndex("runner_capability_grants_active_environment_uq").on(t.organisationId, t.runnerEnvironmentId).where(sql`${t.revokedAt} is null`),
    foreignKey({ columns: [t.organisationId, t.projectId, t.executionCycleId], foreignColumns: [executionCycles.organisationId, executionCycles.projectId, executionCycles.id], name: "runner_capability_grants_cycle_fk" }),
    foreignKey({ columns: [t.organisationId, t.projectId, t.runnerEnvironmentId], foreignColumns: [runnerEnvironments.organisationId, runnerEnvironments.projectId, runnerEnvironments.id], name: "runner_capability_grants_environment_fk" }),
    check("runner_capability_grants_expiry_ck", sql`${t.expiresAt} > ${t.issuedAt}`),
    check("runner_capability_grants_revocation_ck", sql`(${t.revokedAt} is null) = (${t.revokedReason} is null)`),
  ],
);

export const runnerEnvironmentEvents = pgTable(
  "runner_environment_events",
  {
    id: id(),
    organisationId: uuid("organisation_id").notNull(),
    projectId: uuid("project_id").notNull(),
    runnerEnvironmentId: uuid("runner_environment_id").notNull(),
    sequence: integer("sequence").notNull(),
    fromState: text("from_state"),
    toState: text("to_state").notNull(),
    safeMetadata: requiredJsonObject("safe_metadata"),
    correlationId: uuid("correlation_id").notNull(),
    occurredAt: timestamp("occurred_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    unique("runner_environment_events_org_id_uq").on(t.organisationId, t.id),
    unique("runner_environment_events_environment_sequence_uq").on(t.organisationId, t.runnerEnvironmentId, t.sequence),
    foreignKey({ columns: [t.organisationId, t.projectId, t.runnerEnvironmentId], foreignColumns: [runnerEnvironments.organisationId, runnerEnvironments.projectId, runnerEnvironments.id], name: "runner_environment_events_environment_fk" }),
  ],
);

export const agentRuns = pgTable(
  "agent_runs",
  {
    id: id(),
    organisationId: uuid("organisation_id").notNull(),
    projectId: uuid("project_id").notNull(),
    executionCycleId: uuid("execution_cycle_id").notNull(),
    runnerEnvironmentId: uuid("runner_environment_id").notNull(),
    provider: text("provider").notNull(),
    externalThreadReference: text("external_thread_reference"),
    externalProcessReference: text("external_process_reference"),
    state: text("state").default("starting").notNull(),
    attempt: integer("attempt").notNull(),
    startedAt: timestamp("started_at", { withTimezone: true }),
    stoppedAt: timestamp("stopped_at", { withTimezone: true }),
    stopReason: text("stop_reason"),
  },
  (t) => [
    unique("agent_runs_org_id_uq").on(t.organisationId, t.id),
    unique("agent_runs_project_id_uq").on(t.organisationId, t.projectId, t.id),
    unique("agent_runs_cycle_attempt_uq").on(t.organisationId, t.executionCycleId, t.attempt),
    foreignKey({ columns: [t.organisationId, t.projectId, t.executionCycleId], foreignColumns: [executionCycles.organisationId, executionCycles.projectId, executionCycles.id], name: "agent_runs_cycle_fk" }),
    foreignKey({ columns: [t.organisationId, t.projectId, t.runnerEnvironmentId], foreignColumns: [runnerEnvironments.organisationId, runnerEnvironments.projectId, runnerEnvironments.id], name: "agent_runs_environment_fk" }),
    check("agent_runs_state_ck", sql`${t.state} in ('starting','running','stopped','failed')`),
    check("agent_runs_attempt_ck", sql`${t.attempt} > 0`),
  ],
);

export const agentTurns = pgTable(
  "agent_turns",
  {
    id: id(),
    organisationId: uuid("organisation_id").notNull(),
    projectId: uuid("project_id").notNull(),
    executionCycleId: uuid("execution_cycle_id").notNull(),
    agentRunId: uuid("agent_run_id").notNull(),
    sequence: integer("sequence").notNull(),
    state: text("state").default("requested").notNull(),
    inputManifestHash: text("input_manifest_hash").notNull(),
    outputManifestHash: text("output_manifest_hash"),
    providerResponseId: text("provider_response_id"),
    usageSummary: requiredJsonObject("usage_summary"),
    startedAt: timestamp("started_at", { withTimezone: true }),
    endedAt: timestamp("ended_at", { withTimezone: true }),
  },
  (t) => [
    unique("agent_turns_org_id_uq").on(t.organisationId, t.id),
    unique("agent_turns_project_id_uq").on(t.organisationId, t.projectId, t.id),
    unique("agent_turns_run_sequence_uq").on(t.organisationId, t.agentRunId, t.sequence),
    foreignKey({ columns: [t.organisationId, t.projectId, t.agentRunId], foreignColumns: [agentRuns.organisationId, agentRuns.projectId, agentRuns.id], name: "agent_turns_run_fk" }),
    check("agent_turns_state_ck", sql`${t.state} in ('requested','running','completed','failed','cancelled')`),
  ],
);

export const agentActions = pgTable(
  "agent_actions",
  {
    id: id(),
    organisationId: uuid("organisation_id").notNull(),
    projectId: uuid("project_id").notNull(),
    executionCycleId: uuid("execution_cycle_id").notNull(),
    agentTurnId: uuid("agent_turn_id").notNull(),
    sequence: integer("sequence").notNull(),
    actionType: text("action_type").notNull(),
    targetSummary: text("target_summary").notNull(),
    policyDecision: text("policy_decision").notNull(),
    status: text("status").notNull(),
    exitCode: integer("exit_code"),
    errorClassification: text("error_classification"),
    safeMetadata: requiredJsonObject("safe_metadata"),
    rawObjectReference: text("raw_object_reference"),
    rawObjectExpiresAt: timestamp("raw_object_expires_at", { withTimezone: true }),
    occurredAt: timestamp("occurred_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    unique("agent_actions_org_id_uq").on(t.organisationId, t.id),
    unique("agent_actions_turn_sequence_uq").on(t.organisationId, t.agentTurnId, t.sequence),
    foreignKey({ columns: [t.organisationId, t.projectId, t.agentTurnId], foreignColumns: [agentTurns.organisationId, agentTurns.projectId, agentTurns.id], name: "agent_actions_turn_fk" }),
    index("agent_actions_cycle_time_idx").on(t.organisationId, t.executionCycleId, t.occurredAt),
    check("agent_actions_policy_ck", sql`${t.policyDecision} in ('allowed','denied')`),
    check("agent_actions_status_ck", sql`${t.status} in ('planned','started','completed','failed','denied','cancelled')`),
    check("agent_actions_denied_effect_ck", sql`${t.policyDecision} <> 'denied' or ${t.status} = 'denied'`),
  ],
);

export const executionCheckpoints = pgTable(
  "execution_checkpoints",
  {
    id: id(),
    organisationId: uuid("organisation_id").notNull(),
    projectId: uuid("project_id").notNull(),
    executionCycleId: uuid("execution_cycle_id").notNull(),
    sequence: integer("sequence").notNull(),
    kind: text("kind").notNull(),
    status: text("status").default("open").notNull(),
    requestedDecision: text("requested_decision"),
    snapshotReference: text("snapshot_reference"),
    workReportId: uuid("work_report_id"),
    createdAt: createdAt(),
    resolvedAt: timestamp("resolved_at", { withTimezone: true }),
    resolvedByPrincipalId: uuid("resolved_by_principal_id"),
    resolution: text("resolution"),
  },
  (t) => [
    unique("execution_checkpoints_org_id_uq").on(t.organisationId, t.id),
    unique("execution_checkpoints_cycle_sequence_uq").on(t.organisationId, t.executionCycleId, t.sequence),
    foreignKey({ columns: [t.organisationId, t.projectId, t.executionCycleId], foreignColumns: [executionCycles.organisationId, executionCycles.projectId, executionCycles.id], name: "execution_checkpoints_cycle_fk" }),
    check("execution_checkpoints_kind_ck", sql`${t.kind} in ('planned','human_input','scope_denial','failure','limit')`),
    check("execution_checkpoints_status_ck", sql`${t.status} in ('open','resolved','superseded')`),
  ],
);

export const executionUsageEvents = pgTable(
  "execution_usage_events",
  {
    id: id(),
    organisationId: uuid("organisation_id").notNull(),
    projectId: uuid("project_id").notNull(),
    executionCycleId: uuid("execution_cycle_id").notNull(),
    agentRunId: uuid("agent_run_id"),
    agentTurnId: uuid("agent_turn_id"),
    usageKind: text("usage_kind").notNull(),
    quantity: bigint("quantity", { mode: "number" }).notNull(),
    unit: text("unit").notNull(),
    costMinorUnits: bigint("cost_minor_units", { mode: "number" }).default(0).notNull(),
    currency: text("currency").notNull(),
    providerEventId: text("provider_event_id").notNull(),
    occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull(),
  },
  (t) => [
    unique("execution_usage_events_org_id_uq").on(t.organisationId, t.id),
    unique("execution_usage_events_provider_event_uq").on(t.providerEventId),
    foreignKey({ columns: [t.organisationId, t.projectId, t.executionCycleId], foreignColumns: [executionCycles.organisationId, executionCycles.projectId, executionCycles.id], name: "execution_usage_events_cycle_fk" }),
    index("execution_usage_events_cycle_time_idx").on(t.organisationId, t.executionCycleId, t.occurredAt),
    check("execution_usage_events_nonnegative_ck", sql`${t.quantity} >= 0 and ${t.costMinorUnits} >= 0`),
  ],
);

export const executionTestRuns = pgTable(
  "execution_test_runs",
  {
    id: id(),
    organisationId: uuid("organisation_id").notNull(),
    projectId: uuid("project_id").notNull(),
    executionCycleId: uuid("execution_cycle_id").notNull(),
    testDefinitionManifest: requiredJsonObject("test_definition_manifest"),
    commandManifest: requiredJsonObject("command_manifest"),
    status: text("status").default("requested").notNull(),
    startedAt: timestamp("started_at", { withTimezone: true }),
    completedAt: timestamp("completed_at", { withTimezone: true }),
    summary: requiredJsonObject("summary"),
    rawObjectReference: text("raw_object_reference"),
    rawObjectExpiresAt: timestamp("raw_object_expires_at", { withTimezone: true }),
  },
  (t) => [
    unique("execution_test_runs_org_id_uq").on(t.organisationId, t.id),
    unique("execution_test_runs_project_id_uq").on(t.organisationId, t.projectId, t.id),
    foreignKey({ columns: [t.organisationId, t.projectId, t.executionCycleId], foreignColumns: [executionCycles.organisationId, executionCycles.projectId, executionCycles.id], name: "execution_test_runs_cycle_fk" }),
    check("execution_test_runs_status_ck", sql`${t.status} in ('requested','running','passed','failed','cancelled','error')`),
  ],
);

export const executionWorkReports = pgTable(
  "execution_work_reports",
  {
    id: id(),
    organisationId: uuid("organisation_id").notNull(),
    projectId: uuid("project_id").notNull(),
    executionCycleId: uuid("execution_cycle_id").notNull(),
    versionNumber: integer("version_number").notNull(),
    structuredSchemaVersion: text("structured_schema_version").notNull(),
    structuredPayload: jsonb("structured_payload").$type<Record<string, unknown>>().notNull(),
    plainLanguageSummary: text("plain_language_summary").notNull(),
    technicalSummary: text("technical_summary").notNull(),
    stopReason: text("stop_reason").notNull(),
    contentHash: text("content_hash").notNull(),
    supersedesWorkReportId: uuid("supersedes_work_report_id"),
    createdAt: createdAt(),
  },
  (t) => [
    unique("execution_work_reports_org_id_uq").on(t.organisationId, t.id),
    unique("execution_work_reports_project_id_uq").on(t.organisationId, t.projectId, t.id),
    unique("execution_work_reports_cycle_version_uq").on(t.organisationId, t.executionCycleId, t.versionNumber),
    unique("execution_work_reports_cycle_hash_uq").on(t.organisationId, t.executionCycleId, t.contentHash),
    foreignKey({ columns: [t.organisationId, t.projectId, t.executionCycleId], foreignColumns: [executionCycles.organisationId, executionCycles.projectId, executionCycles.id], name: "execution_work_reports_cycle_fk" }),
  ],
);

export const executionReviews = pgTable(
  "execution_reviews",
  {
    id: id(),
    organisationId: uuid("organisation_id").notNull(),
    projectId: uuid("project_id").notNull(),
    executionCycleId: uuid("execution_cycle_id").notNull(),
    executionWorkReportId: uuid("execution_work_report_id").notNull(),
    reviewerProjectMembershipId: uuid("reviewer_project_membership_id").notNull(),
    reviewType: text("review_type").notNull(),
    decision: text("decision").notNull(),
    comments: text("comments"),
    conditions: jsonb("conditions").$type<readonly Record<string, unknown>[]>().default([]).notNull(),
    createdAt: createdAt(),
  },
  (t) => [
    unique("execution_reviews_org_id_uq").on(t.organisationId, t.id),
    foreignKey({ columns: [t.organisationId, t.projectId, t.executionCycleId], foreignColumns: [executionCycles.organisationId, executionCycles.projectId, executionCycles.id], name: "execution_reviews_cycle_fk" }),
    foreignKey({ columns: [t.organisationId, t.projectId, t.executionWorkReportId], foreignColumns: [executionWorkReports.organisationId, executionWorkReports.projectId, executionWorkReports.id], name: "execution_reviews_report_fk" }),
    foreignKey({ columns: [t.organisationId, t.reviewerProjectMembershipId], foreignColumns: [projectMemberships.organisationId, projectMemberships.id], name: "execution_reviews_membership_fk" }),
    index("execution_reviews_cycle_type_idx").on(t.organisationId, t.executionCycleId, t.reviewType, t.createdAt),
    check("execution_reviews_type_ck", sql`${t.reviewType} in ('technical','stakeholder','checkpoint')`),
    check("execution_reviews_decision_ck", sql`${t.decision} in ('approved','approved_with_conditions','changes_requested','rejected')`),
  ],
);

export const codeChanges = pgTable(
  "code_changes",
  {
    id: id(),
    organisationId: uuid("organisation_id").notNull(),
    projectId: uuid("project_id").notNull(),
    executionCycleId: uuid("execution_cycle_id").notNull(),
    repositoryId: uuid("repository_id").notNull(),
    sideEffectKey: text("side_effect_key").notNull(),
    branch: text("branch").notNull(),
    baseCommitSha: text("base_commit_sha").notNull(),
    headCommitSha: text("head_commit_sha"),
    pullRequestNumber: bigint("pull_request_number", { mode: "number" }),
    pullRequestUrl: text("pull_request_url"),
    pullRequestStatus: text("pull_request_status"),
    intentState: text("intent_state").default("planned").notNull(),
    completionState: text("completion_state").default("pending").notNull(),
    createdAt: createdAt(),
    completedAt: timestamp("completed_at", { withTimezone: true }),
    lockVersion: lockVersion(),
  },
  (t) => [
    unique("code_changes_org_id_uq").on(t.organisationId, t.id),
    unique("code_changes_project_id_uq").on(t.organisationId, t.projectId, t.id),
    unique("code_changes_side_effect_uq").on(t.organisationId, t.sideEffectKey),
    foreignKey({ columns: [t.organisationId, t.projectId, t.executionCycleId], foreignColumns: [executionCycles.organisationId, executionCycles.projectId, executionCycles.id], name: "code_changes_cycle_fk" }),
    foreignKey({ columns: [t.organisationId, t.repositoryId], foreignColumns: [repositories.organisationId, repositories.id], name: "code_changes_repository_fk" }),
  ],
);

export const changedFiles = pgTable(
  "changed_files",
  {
    id: id(),
    organisationId: uuid("organisation_id").notNull(),
    projectId: uuid("project_id").notNull(),
    codeChangeId: uuid("code_change_id").notNull(),
    normalisedPath: text("normalised_path").notNull(),
    changeType: text("change_type").notNull(),
    additions: integer("additions").default(0).notNull(),
    deletions: integer("deletions").default(0).notNull(),
    beforeBlobHash: text("before_blob_hash"),
    afterBlobHash: text("after_blob_hash"),
    createdAt: createdAt(),
  },
  (t) => [
    unique("changed_files_org_id_uq").on(t.organisationId, t.id),
    unique("changed_files_change_path_uq").on(t.organisationId, t.codeChangeId, t.normalisedPath),
    foreignKey({ columns: [t.organisationId, t.projectId, t.codeChangeId], foreignColumns: [codeChanges.organisationId, codeChanges.projectId, codeChanges.id], name: "changed_files_code_change_fk" }),
    check("changed_files_type_ck", sql`${t.changeType} in ('added','modified','deleted','renamed')`),
    check("changed_files_counts_ck", sql`${t.additions} >= 0 and ${t.deletions} >= 0`),
  ],
);
