import {
  asId,
  type ActorId,
  type ApprovalDecisionId,
  type ApprovalPolicyVersionId,
  type ApprovalRequestId,
  type ApprovalRequirementId,
  type ApprovalSnapshotId,
  type ArtifactId,
  type ArtifactVersionId,
  type ExecutionCycleId,
  type ExecutionPlanVersionId,
  type ExecutionWorkItemClaimId,
  type OrganisationId,
  type ProjectId,
  type ProjectMembershipId,
  type QuestionId,
  type QuestionResponseId,
  type KnowledgeSourceId,
  type ReauthenticationGrantId,
  type ReleaseId,
  type ReleaseVersionId,
  type RunnerCapabilityGrantId,
  type RunnerEnvironmentId,
  type SourceFragmentId,
  type UserId,
  type WorkItemId,
} from "../src/index.js";

const id = (counter: number): string =>
  `00000000-0000-7000-8000-${String(counter).padStart(12, "0")}`;

export const IDS = {
  actor: asId<ActorId>(id(1)),
  organisation: asId<OrganisationId>(id(2)),
  otherOrganisation: asId<OrganisationId>(id(3)),
  project: asId<ProjectId>(id(4)),
  otherProject: asId<ProjectId>(id(5)),
  membership: asId<ProjectMembershipId>(id(6)),
  otherMembership: asId<ProjectMembershipId>(id(7)),
  user: asId<UserId>(id(8)),
  otherUser: asId<UserId>(id(9)),
  thirdUser: asId<UserId>(id(10)),
  artifact: asId<ArtifactId>(id(11)),
  artifactVersion: asId<ArtifactVersionId>(id(12)),
  priorArtifactVersion: asId<ArtifactVersionId>(id(13)),
  sourceFragment: asId<SourceFragmentId>(id(14)),
  approvalSnapshot: asId<ApprovalSnapshotId>(id(15)),
  approvalRequest: asId<ApprovalRequestId>(id(16)),
  approvalPolicyVersion: asId<ApprovalPolicyVersionId>(id(17)),
  approvalRequirement: asId<ApprovalRequirementId>(id(18)),
  otherApprovalRequirement: asId<ApprovalRequirementId>(id(19)),
  approvalDecision: asId<ApprovalDecisionId>(id(20)),
  reauthenticationGrant: asId<ReauthenticationGrantId>(id(21)),
  executionPlanVersion: asId<ExecutionPlanVersionId>(id(22)),
  executionCycle: asId<ExecutionCycleId>(id(23)),
  runnerEnvironment: asId<RunnerEnvironmentId>(id(24)),
  runnerCapability: asId<RunnerCapabilityGrantId>(id(25)),
  workItem: asId<WorkItemId>(id(26)),
  otherWorkItem: asId<WorkItemId>(id(27)),
  workItemClaim: asId<ExecutionWorkItemClaimId>(id(28)),
  release: asId<ReleaseId>(id(29)),
  releaseVersion: asId<ReleaseVersionId>(id(30)),
  question: asId<QuestionId>(id(31)),
  response: asId<QuestionResponseId>(id(32)),
  otherResponse: asId<QuestionResponseId>(id(33)),
  knowledgeSource: asId<KnowledgeSourceId>(id(34)),
  otherSourceFragment: asId<SourceFragmentId>(id(35)),
} as const;

export const NOW = new Date("2026-07-22T00:00:00.000Z");
